apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: gate-portable-data
  labels:
    app: gate-portable
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
