apiVersion: v1
kind: Service
metadata:
  name: gate-portable
  labels:
    app: gate-portable
spec:
  selector:
    app: gate-portable
  ports:
    - name: proxy
      port: 8080
      targetPort: proxy
    - name: admin
      port: 9000
      targetPort: admin
    - name: metrics
      port: 9090
      targetPort: metrics
