apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: gate-standalone-data
  labels:
    app: gate-standalone
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
