apiVersion: v1
kind: Service
metadata:
  name: {{ include "gate.fullname" . }}-admin
  labels:
    {{- include "gate.labels" . | nindent 4 }}
    {{- include "gate.admin.selectorLabels" . | nindent 4 }}
spec:
  type: {{ .Values.admin.service.type }}
  ports:
    - name: admin
      port: {{ .Values.admin.service.port }}
      targetPort: admin
      protocol: TCP
  selector:
    {{- include "gate.admin.selectorLabels" . | nindent 4 }}
