{{- if not .Values.secrets.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "gate.fullname" . }}
  labels:
    {{- include "gate.labels" . | nindent 4 }}
type: Opaque
stringData:
  ADMIN_TOKEN: {{ .Values.secrets.adminToken | quote }}
  DATABASE_URL: {{ include "gate.databaseUrl" . | quote }}
  {{- with (include "gate.redisUrl" .) }}
  {{- if . }}
  REDIS_URL: {{ . | quote }}
  {{- end }}
  {{- end }}
{{- end }}
