apiVersion: v1
kind: ConfigMap
metadata:
  name: gate-java-config
data:
  PROXY: |
    [
      { "name": "users", "ip": "users-service", "port": 8080 },
      { "name": "orders", "ip": "orders-service", "port": 8080 },
      { "name": "products", "ip": "products-service", "port": 8080, "api-key": "change-me", "tls": true }
    ]
