apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: gate-proxy-ingress
  namespace: gate
  labels:
    app.kubernetes.io/name: gate
    app.kubernetes.io/component: proxy
  annotations:
    cert-manager.io/cluster-issuer: k8s-sub-ca
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  ingressClassName: nginx
  rules:
    - host: gate.k8s.lab
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: gate-proxy
                port:
                  name: proxy
  tls:
    - hosts:
        - gate.k8s.lab
      secretName: gate-lab-tls
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: gate-admin-ingress
  namespace: gate
  labels:
    app.kubernetes.io/name: gate
    app.kubernetes.io/component: admin
  annotations:
    cert-manager.io/cluster-issuer: k8s-sub-ca
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  ingressClassName: nginx
  rules:
    - host: gate-admin.k8s.lab
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: gate-admin
                port:
                  name: admin
  tls:
    - hosts:
        - gate-admin.k8s.lab
      secretName: gate-admin-lab-tls
